apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ada-vcs
  name: ada-vcs
spec:
  selector:
    matchLabels:
      app: ada-vcs
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ada-vcs
        actorSystemName: ada
    spec:
      containers:
      - name: ada-vcs
        image: ada-vcs
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: remoting
          containerPort: 2551
          protocol: TCP
        - name: management
          containerPort: 8558
          protocol: TCP
        env:
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_NAMESPACE
          value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: ada-vcs
  labels:
    app: ada-vcs
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: management
    protocol: TCP
    port: 8558
    targetPort: management
  - name: api
    protocol: TCP
    port: 2551
    targetPort: api
  selector:
    app: ada-vcs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
