kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "build-config"
spec:
  source:
    git:
      uri: "https://github.com/cokeSchlumpf/ada"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
